# vim: ft=yaml
---
driver:
  name: docker

provisioner:
  name: salt_solo
  is_file_root: true
  sudo: false
  salt_copy_filter:
    - .kitchen
    - .git
    - .vagrant
  state_top:
    base:
      "*":
        - test.mockup
        - openldap

platforms:
  - name: debian-8

suites:
  - name: default

  - name: custom
    provisioner:
      pillars-from-files:
        openldap.sls: pillar-custom.sls
      pillars:
        top.sls:
          base:
            "*":
              - openldap
